# Generated by Django 4.0.6 on 2022-08-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCateg',
            fields=[
                ('categId', models.AutoField(primary_key=True, serialize=False)),
                ('categName', models.CharField(max_length=100)),
            ],
        ),
    ]
