# Generated by Django 4.0.6 on 2022-08-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_addnotes_ncateg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnotes',
            name='ncateg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.addcateg'),
        ),
    ]
