# Generated by Django 4.1 on 2022-09-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('cdno', models.AutoField(primary_key=True, serialize=False)),
                ('cdname', models.CharField(max_length=100)),
                ('cdemail', models.CharField(max_length=100)),
                ('cdsubject', models.TextField()),
                ('cdmessage', models.TextField()),
            ],
        ),
    ]
