# Generated by Django 4.1 on 2022-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=100)),
                ('ncateg', models.CharField(max_length=100)),
                ('ndesc', models.TextField(null=True)),
                ('nimg', models.FileField(default=None, max_length=500, null=True, upload_to='notes/')),
                ('nfile', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
