# Generated by Django 4.0.6 on 2022-08-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_addcateg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnotes',
            name='ncateg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.addcateg'),
        ),
    ]
