# Generated by Django 4.0.6 on 2022-08-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0009_jobapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_save',
            name='numofjobs',
            field=models.IntegerField(default=0),
        ),
    ]
