# Generated by Django 4.0.6 on 2022-09-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0013_remove_stu_appliedjobs_jobuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_save',
            name='numofjobs',
            field=models.IntegerField(default=0),
        ),
    ]
