# Generated by Django 4.0.6 on 2022-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0014_student_save_numofjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_appliedjobs',
            old_name='jccode',
            new_name='jscode',
        ),
        migrations.RemoveField(
            model_name='stu_appliedjobs',
            name='collage_id',
        ),
        migrations.AddField(
            model_name='stu_appliedjobs',
            name='jsemail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
