# Generated by Django 4.0.6 on 2022-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0003_alter_company_save_companyemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_save',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='student_save',
            name='spassword',
        ),
    ]
