# Generated by Django 4.0.6 on 2022-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_save',
            old_name='city',
            new_name='ccity',
        ),
        migrations.RenameField(
            model_name='company_save',
            old_name='password',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='student_save',
            old_name='city',
            new_name='scity',
        ),
        migrations.RenameField(
            model_name='student_save',
            old_name='email',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='student_save',
            old_name='password',
            new_name='spassword',
        ),
    ]
