# Generated by Django 4.0.6 on 2022-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0006_company_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_save',
            name='hper',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='hschool',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='hsession',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='intname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='intper',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='intsession',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='iper',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='ischool',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='isession',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='lqname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_save',
            name='lqtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company_jobs',
            name='cdesc',
            field=models.TextField(),
        ),
    ]
