# Generated by Django 4.0.6 on 2022-08-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0008_student_save_skills_alter_student_save_intper'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jccode', models.CharField(max_length=10)),
                ('jsname', models.CharField(max_length=100)),
                ('jpnum', models.CharField(max_length=100)),
                ('jemail', models.CharField(max_length=100)),
                ('jport', models.CharField(max_length=100)),
                ('jcurrent', models.CharField(max_length=100)),
                ('jreason', models.TextField()),
                ('jsum', models.TextField()),
                ('jresume', models.FileField(default=None, max_length=500, null=True, upload_to='jobapply/')),
            ],
        ),
    ]
