# Generated by Django 4.0.6 on 2022-08-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement_system', '0011_remove_student_save_numofjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_appliedjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_system.company_jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_system.student_save')),
            ],
        ),
    ]
